language: node_js
node_js:
  - 12
install:
  - npm install
cache:
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: "pmjonesg-github"
    token: $SONAR_TOKEN
script:
  - npm test
  - sonar-scanner
